version: '3.7'
services:
  mongodb:
    image: mongo
    
    container_name: my-mongodb
    ports:
      - "27017:27017"
      
  AuthProject:
    image: hanihaddad/auth_project:backend-builder
    build:
      context: ./
      dockerfile: ./AuthProject/AuthProject/docker/builder.Dockerfile
    
    volumes:
      - ./AuthProject/AuthProject:/app/AuthProject
      - ./SharedModelNamespace/SharedModelNamespace:/app/SharedModelNamespace
    command: [  "watch", "run"]
    ports:
      - "5060:5060"

  CRUDAPI:
    image: hanihaddad/crudapi:crud-backend-builder
    build:
      context: ./
      dockerfile: ./CRUDAPI/docker/builder.Dockerfile
    
    volumes:
      - ./CRUDAPI:/app/CRUDAPI
      - ./SharedModelNamespace/SharedModelNamespace:/app/SharedModelNamespace
    command: [  "watch", "run"]
    ports:
      - "5055:5055"